config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {
                 :registrations => 'devise_override/registrations',
                 :sessions      => 'devise_override/sessions'
             },
             :path_names  => {
                 :verify_authy              => "/verify-token",
                 :enable_authy              => "/enable-two-factor",
                 :verify_authy_installation => "/verify-installation"
             }

  ActiveAdmin.routes(self)

  root 'products#index'
  # --------------------------------------

  resource :cart do
    member { delete :destroy }
    collection do
      post :checkout
      post :pre_checkout
    end
  end

  resources :products do
    collection { get :search }
  end

  resources :orders
  get '/profile', to: 'profile#show'
  post "authy/callback"
  get "authy/status" => 'authy#one_touch_status'
  post "authy/send_token_via_sms"
  post "authy/verify"
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  status     :integer
#  metadata   :jsonb
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
  belongs_to :customer, foreign_key: :user_id

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  accepts_nested_attributes_for :cart_items
  alias items cart_items

  def total
    cart_items.total_amount
  end
  def total_tax
    cart_items.total_tax_amount
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!, except: [:checkout, :pre_checkout]
  before_action :authenticate_only_customer!, only: [:checkout, :pre_checkout]
  before_action :verify_token, only: [:checkout]
  before_action :no_empty_cart!, only: [:checkout, :pre_checkout]

  def show
  end

  def create
    session[:cart_id] = Cart.create(cart_params).id
    flash[:notice]    = 'Item added to cart successfully.'
    redirect_to :back
  end

  def update
    cart = Cart.find(session[:cart_id])
    cart.update(cart_params)
    flash[:notice] = 'Item added to cart successfully.'
    redirect_to :back
  end

  def destroy
    cart_item = @cart.items.find(params[:id])
    if cart_item.destroy
      flash[:notice] = 'Item successfully removed from the cart'
    else
      flash[:error] = 'Could not complete the operation due to some error'
    end
    redirect_back fallback_location: root_path
  end

  def pre_checkout
    # Empty the `authy_status` field of current_user
    # Reason: every 2000ms an AJAX call comes to verify the OneTouch Status.
    #  So clearing the garbage from previous sessions.
    current_user.update(authy_status: nil)

    # Try to verify with OneTouch
    Authy::OneTouch.send_approval_request(
        id:      current_user.authy_id,
        message: "Request to verify checkout to Storify app",
        details: {
            'Gross Amount'  => @cart.items.total_amount + @cart.items.total_tax_amount,
            'Products' => @cart.products.map(&:name).to_s,
            'Email Address' => current_user.email,
        }
    )
  end

  def checkout
    # Generate Order and Line Items from Cart and CartItems
    # Delete Cart and CartItems
    line_items = @cart.cart_items.map do |cart_item|
      LineItem.create({ product_id: cart_item.product_id })
    end

    if order = Order.create(user_id: current_user.id, line_items: line_items)
      flash[:notice] = 'You have successfully ordered the items in the cart. Products have been delivedred via Email.'
      @cart.destroy
      CartMailer.deliver(order.id).deliver_now
    else
      flash[:error] = 'Could not complete the operation due to some error'
    end

    redirect_to cart_path
  end

  private

  def verify_token
    if current_user.authy_status.present? || valid_token?
      current_user.update(authy_status: nil)
    else
      flash[:error] = 'Authentication could not be completed. Please try again'
      redirect_back fallback_location: root_path
    end
  end

  def cart_params
    params.require(:cart).permit(cart_items_attributes: [:id, :product_id])
  end

  def valid_token?
    Authy::API.verify(id: current_user.authy_id, token: params[:token]).ok?
  end

  def invalid_token?
    !valid_token?
  end

  def no_empty_cart!
    if @cart.cart_items.empty?
      flash[:error] = 'Please put items into cart before checkout'
      redirect_to root_path
    end
  end
end

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      ul
        - @cart.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :status
    = f.number_field :status
  .field
    = f.label :metadata
    = f.text_field :metadata
  .actions = f.submit

app/views/carts/pre_checkout.slim
h2.with-busy-icon
  | One touch verification in progress ..
.row
  .col-md-5
    p
      | A one touch verification request has been sent to you mobile
      |  device already. Please approve the request to proceed further.
    p Thanks!
  .col-md-6

hr
h2 Verify via Soft-token
p
  | If you are having difficulty with One-Touch, you can verify via soft-token
.well
  = form_tag checkout_cart_path, method: :post, id: 'verification-form' do
    .row
      .form-group.col-md-6
        = label_tag :token, 'Token from Mobile Device'
        = text_field_tag :token, nil, class: 'form-control'

    = link_to 'Send token Via SMS', authy_send_token_via_sms_path, remote: true, method: :post
    = submit_tag 'Verify', id: 'verify-token', class: 'margin20left'

app/views/carts/show.slim
h1 Cart
- if @cart.items.present?
  h3 Cart Items
  - @cart.items.each do |item|
    .panel.panel-default
      .panel-body

        .col-md-2.margin10top
          = link_to item.product do
            = image_tag item.product.first_image, class: 'img-responsive'
        .col-md-10
          = link_to item.product do
            h4
              = item.product.name
              span.small
                - if item.product.author.present?
                  |  by&nbsp;
                  = item.product.author
          hr
          = item.product.description
          .clearfix
          .row.margin10top
            .col-md-6
              table.table.table-striped
                tr
                  th Price
                  td = number_to_currency item.product.selling_price
          = link_to cart_path(id: item), method: :delete, class: 'btn btn-danger' do
            | Remove from Cart
  .row
    .col-md-6
      table.table.table-striped
        tr
          th Total Price
          td = number_to_currency @cart.items.total_amount
        tr
          th Total Tax
          td = number_to_currency @cart.items.total_tax_amount
        tr
          th Grand Total
          td = number_to_currency @cart.items.total_amount + @cart.items.total_tax_amount

  = link_to pre_checkout_cart_path, method: :post, class: 'btn btn-primary' do
    | Checkout
- else
  h3 No Item in the cart. Would you like to buy some?
  = link_to 'Shop', root_path