config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {
                 :registrations => 'devise_override/registrations',
                 :sessions      => 'devise_override/sessions'
             },
             :path_names  => {
                 :verify_authy              => "/verify-token",
                 :enable_authy              => "/enable-two-factor",
                 :verify_authy_installation => "/verify-installation"
             }

  ActiveAdmin.routes(self)

  root 'products#index'
  # --------------------------------------

  resource :cart do
    member { delete :destroy }
    collection do
      post :checkout
      post :pre_checkout
    end
  end

  resources :products do
    collection { get :search }
  end

  resources :orders
  get '/profile', to: 'profile#show'
  post "authy/callback"
  get "authy/status" => 'authy#one_touch_status'
  post "authy/send_token_via_sms"
  post "authy/verify"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  # Note: Any before_action declared here must be skipped via active_admin.rb

  include ExceptionHandler

  before_action :authenticate_user!
  before_action :set_categories
  before_action :set_cart

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_categories
    @categories = Category.master
  end

  def set_cart
    @cart = Cart.find_or_initialize_by(id: session[:cart_id])
  end

  def configure_permitted_parameters
    # Some override has been done in DeviseOverride::RegistrationsController
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:email,
                                             :first_name,
                                             :last_name,
                                             :gender,
                                             :avatar,
                                             :password,
                                             :password_confirmation,
                                             :country_code,
                                             :phone_number,
                                             :type])

  end

  def authenticate_only_customer!
    unless current_user&.customer?
      raise UnAuthorized
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_message.slim
- if flash[:notice].present?
  .the-flash.alert.alert-success.main_alert[role="alert"]
    a.close href="#" data-dismiss="alert" aria-label="close" &times;
    = flash[:notice]
- elsif flash[:error].present?
  .the-flash.alert.alert-danger.main_alert[role="alert"]
    a.close href="#" data-dismiss="alert" aria-label="close" &times;
    = flash[:error]

/ Alert might coexists with other flash types
- if flash[:alert].present?
  .the-flash.alert.alert-warning.main_alert[role="alert"]
    a.close href="#" data-dismiss="alert" aria-label="close" &times;
    = flash[:alert]

app/views/application/_footer.slim
footer.footer-distributed
  .footer-left
    .links
      p.footer-links
        a[href="#"]
          | Home
        br
        a[href="#"]
          | Blog
        br
        a[href="#"]
          | Pricing
        br
        a[href="#"]
          | About
        br
        a[href="#"]
          | Faq
        br
        a[href="#"]
          | Contact
    p.footer-company-name
      | Storify © 2017
  .footer-center
    div
      i.fa.fa-map-marker
      p
        span
          | 21 Revolution Street
        |  Paris, France
    div
      i.fa.fa-phone
      p
        | +1 555 123456
    div
      i.fa.fa-envelope
      p
        a[href="mailto:support@company.com"]
          | support@storify.net
  .footer-right
    p.footer-company-about
      span
        | About Storify
      |  Storify is built keeping in mind that this project could be used as a framework for building
      |  E-Commerce store-front application. This provides you with admin panel for store keeper.
    .footer-icons
      a[href="#"]
        i.fa.fa-facebook
      a[href="#"]
        i.fa.fa-twitter
      a[href="#"]
        i.fa.fa-linkedin
      a[href="#"]
        i.fa.fa-github

app/views/application/_header.slim
header
  = link_to root_path do
    = image_tag 'logo.png', class: 'logo img-responsive pull-left'

  .pull-right.margin5top
    - if current_user&.customer?
      = link_to orders_path, class: 'btn btn-default margin5left' do
        i.fa.fa-truck
        |  My Orders
      = link_to profile_path, class: 'btn btn-default margin5left'do
        i.fa.fa-user
        | &nbsp;
        = current_user.first_name
        |  's Profile

    = link_to cart_path, class: 'btn btn-default margin5left' do
      i.fa.fa-shopping-cart
      |  Cart &nbsp;
      span.badge
        = @cart.items.count
    - if current_user && current_user&.admin?
      = link_to 'Goto Dashboard', super_user_dashboard_path, class: 'btn btn-default margin5left'
    - if current_user.present?
      = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-default margin5left'
    - else
      = link_to new_user_session_path, class: 'btn btn-default margin5left' do
        i.fa.fa-sign-in
        |  Sign In
      = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default margin5left'

app/views/application/_sidebar.slim
.panel.panel-default.margin150top
  .panel-heading Categories
  .panel-body
    ul.list-group
      - @categories.each do |category|
        a href=""
          li.list-group-item #{category.name}
        ul
          - category.children.each do|child_cat|
            = link_to search_products_path('search-categories': [child_cat.id]) do
              li.list-group-item #{child_cat.name}