config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {
                 :registrations => 'devise_override/registrations',
                 :sessions      => 'devise_override/sessions'
             },
             :path_names  => {
                 :verify_authy              => "/verify-token",
                 :enable_authy              => "/enable-two-factor",
                 :verify_authy_installation => "/verify-installation"
             }

  ActiveAdmin.routes(self)

  root 'products#index'
  # --------------------------------------

  resource :cart do
    member { delete :destroy }
    collection do
      post :checkout
      post :pre_checkout
    end
  end

  resources :products do
    collection { get :search }
  end

  resources :orders
  get '/profile', to: 'profile#show'
  post "authy/callback"
  get "authy/status" => 'authy#one_touch_status'
  post "authy/send_token_via_sms"
  post "authy/verify"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  name             :string
#  description      :text
#  sku              :string
#  slug             :string
#  meta_title       :string
#  meta_tags        :string
#  meta_description :text
#  tags             :string
#  metadata         :jsonb            default("{}")
#  available_from   :datetime
#  available_upto   :datetime
#  selling_price    :float
#  cost_price       :float
#  tax_rate         :float            default("0.0")
#  status           :integer          default("0")
#  owner_id         :integer
#  payload          :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Product < ApplicationRecord
  PerPage = 8
  paginates_per PerPage
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :line_items
  has_many :orders, through: :line_items

  has_many :cart_items
  has_many :carts, through: :cart_items

  enum status: [:draft, :published]
  mount_uploader :payload, ProductUploader
  store :metadata, accessors: [:isbn, :author, :publisher, :genre, :pages]

  # Setting for indexing data
  searchable do
    text :name, :description
    integer :categories, multiple: true do
      categories.ids
    end

    boolean :status
    time :created_at
    time :updated_at
    double :selling_price
  end

  def first_image
    pictures.first&.payload || Config::DefaultCoverFileName
  end

  def first_image_thumb
    pictures.first&.payload.thumb || Config::DefaultCoverFileName
  end

  private
  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
        :name,
        [:name, :sku]
    ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @products = Product.order(created_at: :desc).page(params[:page])
  end

  def show
    @cart.cart_items.build
    @product = Product.friendly.find(params[:id])
  end

  def search
    range       = params[:price] && params[:price].split(',').map { |x| x.to_f }
    @categories = Category.all
    @products   = Product.solr_search do
      fulltext params[:q]
      with(:selling_price).between(range[0]..range[1]) if params[:price].present?
      with(:categories, params['search-categories']&.map(&:to_i)) if params['search-categories'].present?

      paginate :page => params[:page], :per_page => Product::PerPage
    end.results

    render :index
  end
end

app/views/products/_add_to_cart.slim
= form_for @cart, url: cart_path(@cart) do |f|
  = f.hidden_field 'user_id', value:  @current_user&.id
  = f.fields_for :cart_items do |ff|
    = ff.hidden_field :product_id, value:  ff.object.product_id || @product.id
  .col-md-2
    = f.button  class: 'btn btn-primary' do
      i.glyphicon.glyphicon-shopping-cart
      |  Add to Cart

app/views/products/_product.slim
#product.col-md-4.col-sm-6.col-xs-6.product-list-item [data-hook="products_list_item"
  itemscope=""
  itemtype="https://schema.org/Product" ]

    .panel.panel-default
      .panel-body.text-center.product-body.min350height
        = link_to product_path(product) do
          = image_tag product.first_image, class: 'center-block img-responsive', width: 200
          br
          span.info itemprop="name" title="#{product.name}"
            = product.name
      .panel-footer.text-center
        span itemprop="offers" itemscope="" itemtype="https://schema.org/Offer"
          span.price.selling.lead itemprop="price"
            strong = number_to_currency product.selling_price

app/views/products/_search_bar.slim
/.search-bar.margin40top.margin40bottom
/  = form_tag search_products_path, method: :get, class: 'row' do
/    .col-md-12.form-group
/      = text_field_tag 'q', nil, placeholder: 'I am looking for ...', class: 'form-control width75 pull-left'
/      = submit_tag 'Search', class: 'btn btn-default width20 pull-right'

.navbar.navbar-default
  .container-fluid
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      = form_tag search_products_path, class: 'navbar-form navbar-left', method: :get do
        ul.nav.navbar-nav
          = select_tag 'search-categories',
              options_from_collection_for_select(@categories, 'id','name', params['search-categories']),
              prompt: 'Categories',
              multiple: true
          .form-group.margin20left
            input.form-control[name="q" type="text" placeholder="Search" value="#{params[:q]}"]

            b.margin20left.padding10right
              = number_to_currency Config::LowerLimit
              input [
                name="price"
                id="search-price-slider"
                type="text" class="span2"
                value=""
                data-slider-min="10"
                data-slider-max="1000"
                data-slider-step="5"
                data-slider-value="[#{params[:price] || '1,145'}]"]

              b.padding10left
                = number_to_currency Config::UpperLimit
            button.margin20left.btn.btn-default[type="submit"]
              | Search

app/views/products/index.slim
header
  = render 'search_bar'

section
  / This will show the navigation buttons
  .pagination.min100height
    = paginate @products
  .clearfix

  / This will render the products
  hr
  .products
    - if @products.present?
      - @products.each do |product|
        = render 'product', product: product
    - else
      h2 No result found
  .clearfix
  hr
  .pagination
    = paginate @products

app/views/products/show.slim
.product-page.margin30top
  .col-md-2
    - @product.pictures.each do |pic|
      = link_to pic.payload.url, target: '_blank' do
        = image_tag pic.payload,
            class: 'img-rounded thumbnail img-responsive'
  .col-md-10
    h2 = @product.name
    .well
      = @product.description
    .properties
      table#product-properties.table.table-striped data-hook=""
        tbody
          tr.even
            td
              strong SKU
            td = @product.sku
          tr.odd
            td
              strong Price
            td = number_to_currency @product.selling_price
          tr.even
            td
              strong Category
            td
              - @product.categories.each do |cat|
                span.margin5left.label.label-info = cat.name
                |  ,
      .col-md-12
        - if @product.id.in?(@cart.products.ids)
          span.btn.btn-info.disabled
            i.glyphicon.glyphicon-shopping-cart
            |  Added to the Cart
        - else
          = render 'add_to_cart', product: @product